export const listaPalabras:string[]=[
    'MANZANA',
    'BANANA',
    'MANDARINA',
    'HELADERA',
    'CLASIFICAR',
    'FOCALIZAR',
    'PERSEVERAR',
    'SEROTININA',
    'TRANSVERSO',
    'CUALITATIVO',
    'CUANTITATIVO',
    'SECUENCIAL',
    'ELEFANTE',
    'DINOSAURIO',
    'GIRAFA',
    'TIGRE',
    'MURCIELAGO',
    'EDIFICIO',
    'PROGRAMAR',
    'SATURNO']

