export const listaPalabras:string[]=[
    'MANZANA',
    'BANANA',
    'MANDARINA',
    'HELADERA',
    'CLASIFICA',
    'FOCALIZA',
    'PERCEVERA',
    'SEROTININA',
    'TRANSVERSO',
    'CUALITATIVO',
    'CUANTITATIVO',
    'SECUENCIAL',
    'ELEFANTE',
    'DINOSAURIO',
    'GIRAFA',
    'TIGRE',
    'MURCIELAGO',
    'EDIFICIO',
    'PROGRAMAR',
    'SATURNO']

